---

#- hosts: seed-hosts
#  roles:
#  - ../../galaxy/openshift-ansible-contrib/roles/openshift-pv-cleanup

- hosts: localhost
  vars_prompt:
    name: "delete_cluster"
    prompt: "Are you sure you want to delete this cluster? (yes/no)"
    private: no
  pre_tasks:
    - set_fact:
        delete_cluster: "{{ delete_cluster }}"
    - meta: end_play
      when: not delete_cluster

- import_playbook: openstack/delete.yml
  when:
  - hosting_infrastructure == 'openstack'

- import_playbook: aws/delete.yml
  when:
  - hosting_infrastructure == 'aws'
  
- import_playbook: gcp/delete.yml
  when:
  - hosting_infrastructure == 'gcp'  
