---

- hosts: localhost
  pre_tasks:
    - meta: end_play
      when: not delete_cluster
    - import_tasks: ../prep-inventory.yml
  roles:
    - role: ../../../galaxy/openshift-ansible-contrib/roles/openstack-stack
      stack_name: "{{ full_dns_domain }}"
      stack_state: 'absent'
  post_tasks:
    - name: Delete auto provisioned registry
      os_volume: 
        display_name: "{{ full_dns_domain }}-registry"
        state: 'absent'
